# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'sampleObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleObjectiveC
  pod 'AxeptioSDK', :git => 'https://github.com/axeptio/tcf-ios-sdk.git', :branch => 'develop', :tag => '0.1.1'
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'Google-Mobile-Ads-SDK'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

